apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  labels:
    env: production
    tier: backend
    app: configmap
    name: backend-configmap
data:
  # default namespace 기준
  EUREKA_INSTANCE_HOSTNAME: "discovery.egov-msa.svc.cluster.local"
  APIGATEWAY_HOSTNAME: "apigateway.egov-msa.svc.cluster.local"
  SPRING_CLOUD_CONFIG_URI: "http://config.egov-msa.svc.cluster.local:8888"
  MYSQL_HOSTNAME: "mysql.egov-msa.svc.cluster.local"
  RABBITMQ_HOSTNAME: "rabbitmq.egov-msa.svc.cluster.local"
  ZIPKIN_HOSTNAME: "zipkin.egov-msa.svc.cluster.local"
