apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: egov-msa
  labels:
    env: production
    tier: database
    app: configmap
    name: mysql-configmap
data:
  mysql-user: "msaportal"
  mysql-database: "msaportal"
  mysql-allow-empty-password: "1"
  mysql-root-host: "%"
  TZ: Asia/Seoul
  master.cnf: |
    [mysqld]
    log-bin
    character-set-server=utf8mb4
    collation-server=utf8mb4_general_ci
    default-time-zone=Asia/Seoul
  slave.cnf: |
    [mysqld]
    super-read-only
    character-set-server=utf8mb4
    collation-server=utf8mb4_general_ci
    default-time-zone=Asia/Seoul