apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: egov-msa
  labels:
    env: production
    tier: backend
    app: kibana
    name: kibana-service
spec:
  type: NodePort
  selector:
    env: production
    tier: backend
    app: kibana
    name: kibana-pod
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
    nodePort: 30105