apiVersion: v1
kind: Service
metadata:
  name: frontend-portal
  namespace: egov-msa
  labels:
    env: production
    tier: frontend
    app: portal
    name: frontend-portal-service
spec:
  type: NodePort
  ports:
    - name: frontend-portal-http
      port: 3000
      targetPort: 3000
      nodePort: 30112
  selector:
    env: production
    tier: frontend
    app: portal
    name: frontend-portal-pod