apiVersion: v1
kind: Service
metadata:
  name: config
  namespace: egov-msa
  labels:
    env: production
    tier: backend
    app: config
    name: config-service
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    env: production
    tier: backend
    app: config
    name: config-pod