apiVersion: v1
kind: Service
metadata:
  name: frontend-admin
  namespace: egov-msa
  labels:
    env: production
    tier: frontend
    app: admin
    name: frontend-admin-service
spec:
  type: NodePort
  ports:
    - name: frontend-admin-http
      port: 3000
      targetPort: 3000
      nodePort: 30111
  selector:
    env: production
    tier: frontend
    app: admin
    name: frontend-admin-pod