apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: egov-msa
  labels:
    env: production
    tier: database
    app: mysql
    app.kubernetes.io/name: mysql
data:
  mysql-user: "msaportal"
  mysql-database: "msaportal"
  mysql-allow-empty-password: "1"
  mysql-root-host: "%"
  TZ: Asia/Seoul
  primary.cnf: |
    [mysqld]
    log-bin
    character-set-server=utf8mb4
    collation-server=utf8mb4_general_ci
    default-time-zone=Asia/Seoul
  replica.cnf: |
    [mysqld]
    super-read-only
    character-set-server=utf8mb4
    collation-server=utf8mb4_general_ci
    default-time-zone=Asia/Seoul